package view;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ferna
 */
public class menuLogin extends javax.swing.JFrame {

    /**
     * Creates new form loginview
     */
    public menuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSenhaview = new javax.swing.JLabel();
        jLabelUsuarioview = new javax.swing.JLabel();
        jTextFieldUsuarioLogin = new javax.swing.JTextField();
        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        jButtonEntrarLogin = new javax.swing.JButton();
        jLabelImgFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login RHW");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSenhaview.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelSenhaview.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSenhaview.setText("Senha");
        getContentPane().add(jLabelSenhaview, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabelUsuarioview.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelUsuarioview.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsuarioview.setText("Usuario");
        getContentPane().add(jLabelUsuarioview, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        getContentPane().add(jTextFieldUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 280, -1));

        jPasswordFieldSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, -1));

        jButtonEntrarLogin.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEntrarLogin.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonEntrarLogin.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEntrarLogin.setText("Entrar");
        jButtonEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 30));

        jLabelImgFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/imgviewLogin.jpg"))); // NOI18N
        getContentPane().add(jLabelImgFundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaLoginActionPerformed

    private void jButtonEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarLoginActionPerformed
       String user = jTextFieldUsuarioLogin.getText();
       String senha = jPasswordFieldSenhaLogin.getText();
       
       if (user.equals("admin") && senha.equals("12345")){
           new menuPrincipal().setVisible(true);
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
       }
    }//GEN-LAST:event_jButtonEntrarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrarLogin;
    private javax.swing.JLabel jLabelImgFundoLogin;
    private javax.swing.JLabel jLabelSenhaview;
    private javax.swing.JLabel jLabelUsuarioview;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    private javax.swing.JTextField jTextFieldUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
