/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import beans.Empresa;
import dao.EmpresaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class menuCadastroEmp extends javax.swing.JFrame {

    /**
     * Creates new form menuCadastroEmp
     */
    public menuCadastroEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRelatorio = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        campoIDemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        EmpPesquisaID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CampoiDPesquisa = new javax.swing.JTextField();
        jTextFieldCadastroCNPJEmp = new javax.swing.JTextField();
        jLabelCadastroCNPJlEmp = new javax.swing.JLabel();
        jLabelCadastroEmailEmp = new javax.swing.JLabel();
        jTextFieldCadastroEmailEmp = new javax.swing.JTextField();
        jLabelCadastroEndEmp = new javax.swing.JLabel();
        jTextFieldCadastroEndEmp = new javax.swing.JTextField();
        jLabelCadastroNomeEmp = new javax.swing.JLabel();
        jTextFieldCadastroNomeEmp = new javax.swing.JTextField();
        jButtonCadastroInserirFun = new javax.swing.JButton();
        jLabelfundoCadastroEmp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Empresas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRelatorio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRelatorio.setText("Relatório");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 90, -1));

        jButtonExcluir.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jButtonEditar.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));

        campoIDemp.setEnabled(false);
        campoIDemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDempActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, -1));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        EmpPesquisaID.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        EmpPesquisaID.setForeground(new java.awt.Color(0, 0, 0));
        EmpPesquisaID.setText("Pesquisar");
        EmpPesquisaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPesquisaIDActionPerformed(evt);
            }
        });
        getContentPane().add(EmpPesquisaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pesquisar a empresa pelo ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        CampoiDPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoiDPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoiDPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, -1));

        jTextFieldCadastroCNPJEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroCNPJEmpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCadastroCNPJEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 290, -1));

        jLabelCadastroCNPJlEmp.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabelCadastroCNPJlEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroCNPJlEmp.setText("CNPJ");
        getContentPane().add(jLabelCadastroCNPJlEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabelCadastroEmailEmp.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabelCadastroEmailEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroEmailEmp.setText("Email");
        getContentPane().add(jLabelCadastroEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jTextFieldCadastroEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroEmailEmpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCadastroEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 290, -1));

        jLabelCadastroEndEmp.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabelCadastroEndEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroEndEmp.setText("Endereço");
        getContentPane().add(jLabelCadastroEndEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jTextFieldCadastroEndEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroEndEmpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCadastroEndEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, -1));

        jLabelCadastroNomeEmp.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabelCadastroNomeEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroNomeEmp.setText("Nome");
        getContentPane().add(jLabelCadastroNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jTextFieldCadastroNomeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroNomeEmpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCadastroNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 290, -1));

        jButtonCadastroInserirFun.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonCadastroInserirFun.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastroInserirFun.setText("Inserir");
        jButtonCadastroInserirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroInserirFunActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroInserirFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabelfundoCadastroEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/imgviewLogin.jpg"))); // NOI18N
        getContentPane().add(jLabelfundoCadastroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCadastroEndEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroEndEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroEndEmpActionPerformed

    private void jTextFieldCadastroEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroEmailEmpActionPerformed

    private void jTextFieldCadastroCNPJEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroCNPJEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroCNPJEmpActionPerformed

    private void jButtonCadastroInserirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroInserirFunActionPerformed
        // TODO add your handling code here:
        String nomeEmpresa = jTextFieldCadastroNomeEmp.getText();
        String endEmpresa = jTextFieldCadastroEndEmp.getText();
        String emailEmpresa = jTextFieldCadastroEmailEmp.getText();
        String CNPJEmpresa = jTextFieldCadastroCNPJEmp.getText();
        
        Empresa empresa = new Empresa ();
        empresa.setNome(nomeEmpresa);
        empresa.setEndereco(endEmpresa);
        empresa.setEmail(emailEmpresa);
        empresa.setCNPJ(CNPJEmpresa);
        
        EmpresaDAO empresaDAO = new EmpresaDAO();
        empresaDAO.inserir(empresa);
        
        jTextFieldCadastroNomeEmp.setText("");
        jTextFieldCadastroEndEmp.setText("");
        jTextFieldCadastroEmailEmp.setText("");
        jTextFieldCadastroCNPJEmp.setText("");
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonCadastroInserirFunActionPerformed

    private void CampoiDPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoiDPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoiDPesquisaActionPerformed

    private void jTextFieldCadastroNomeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroNomeEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroNomeEmpActionPerformed

    private void EmpPesquisaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPesquisaIDActionPerformed

//BOTÃO PESQUISA ID 
            int idPesquisa = Integer.parseInt(CampoiDPesquisa.getText());
                EmpresaDAO empresaDAO = new EmpresaDAO();
                Empresa empresa = empresaDAO.getEmpresa(idPesquisa);
                if(empresa == null){
                  JOptionPane.showMessageDialog(this,"Empresa não encontrada :(");
                  
                }
                
                else{
                    campoIDemp.setText(String.valueOf(empresa.getId()));
                    jTextFieldCadastroNomeEmp.setText(empresa.getNome());
                    jTextFieldCadastroEndEmp.setText(empresa.getEndereco());
                    jTextFieldCadastroEmailEmp.setText(empresa.getEmail());
                    jTextFieldCadastroCNPJEmp.setText(empresa.getCNPJ());
                    
                    
                }
                
                
                
                
                
    }//GEN-LAST:event_EmpPesquisaIDActionPerformed

    private void campoIDempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDempActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(campoIDemp.getText());
        String nomeEmpresa = jTextFieldCadastroNomeEmp.getText();
        String endEmpresa = jTextFieldCadastroEndEmp.getText();
        String emailEmpresa = jTextFieldCadastroEmailEmp.getText();
        String CNPJEmpresa = jTextFieldCadastroCNPJEmp.getText();
        
        Empresa empresa = new Empresa ();
        empresa.setId(id);
        empresa.setNome(nomeEmpresa);
        empresa.setEndereco(endEmpresa);
        empresa.setEmail(emailEmpresa);
        empresa.setCNPJ(CNPJEmpresa);
        
        EmpresaDAO empresaDAO = new EmpresaDAO();
        empresaDAO.editar(empresa);
        
        campoIDemp.setText("");
        jTextFieldCadastroNomeEmp.setText("");
        jTextFieldCadastroEndEmp.setText("");
        jTextFieldCadastroEmailEmp.setText("");
        jTextFieldCadastroCNPJEmp.setText("");
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
// TODO add your handling code here:
        int id = Integer.parseInt(campoIDemp.getText());
        EmpresaDAO empresaDAO = new EmpresaDAO();
        empresaDAO.excluir(id);
        
        campoIDemp.setText("");
        jTextFieldCadastroNomeEmp.setText("");
        jTextFieldCadastroEndEmp.setText("");
        jTextFieldCadastroEmailEmp.setText("");
        jTextFieldCadastroCNPJEmp.setText("");

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
// TODO add your handling code here:
    menuRelatorioEmp re = new menuRelatorioEmp();
    re.setVisible(true);
        


    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCadastroEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCadastroEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCadastroEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCadastroEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCadastroEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoiDPesquisa;
    private javax.swing.JButton EmpPesquisaID;
    private javax.swing.JTextField campoIDemp;
    private javax.swing.JButton jButtonCadastroInserirFun;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadastroCNPJlEmp;
    private javax.swing.JLabel jLabelCadastroEmailEmp;
    private javax.swing.JLabel jLabelCadastroEndEmp;
    private javax.swing.JLabel jLabelCadastroNomeEmp;
    private javax.swing.JLabel jLabelfundoCadastroEmp;
    private javax.swing.JTextField jTextFieldCadastroCNPJEmp;
    private javax.swing.JTextField jTextFieldCadastroEmailEmp;
    private javax.swing.JTextField jTextFieldCadastroEndEmp;
    private javax.swing.JTextField jTextFieldCadastroNomeEmp;
    // End of variables declaration//GEN-END:variables
}
