/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import beans.Funcionario;
import dao.FuncionarioDAO;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class menuCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form menuCadastroFuncionario
     */
    public menuCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRelatorio = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        Editarfun = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonPesquisafun = new javax.swing.JButton();
        pesquisaIDFun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoEmailFun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoEmpresaFun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoCPFFun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoNomefun = new javax.swing.JTextField();
        jButtonInserirFun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Funcionários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRelatorio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRelatorio.setText("Relatório");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jButtonExcluir.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        Editarfun.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        Editarfun.setForeground(new java.awt.Color(0, 0, 0));
        Editarfun.setText("Editar ");
        Editarfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarfunActionPerformed(evt);
            }
        });
        getContentPane().add(Editarfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, -1));

        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, -1));

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButtonPesquisafun.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonPesquisafun.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPesquisafun.setText("Pesquisar ");
        jButtonPesquisafun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisafunActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisafun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        pesquisaIDFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaIDFunActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisaIDFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 50, -1));

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pesquisar funcionário pelo ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        CampoEmailFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailFunActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmailFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 330, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("EMPRESA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        CampoEmpresaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmpresaFunActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmpresaFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 330, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        CampoCPFFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCPFFunActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCPFFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 330, -1));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));

        CampoNomefun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomefunActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNomefun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, -1));

        jButtonInserirFun.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jButtonInserirFun.setForeground(new java.awt.Color(0, 0, 0));
        jButtonInserirFun.setText("Inserir");
        jButtonInserirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirFunActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserirFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/imgviewLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirFunActionPerformed

        // TODO add your handling code here:
        String nome = CampoNomefun.getText();
        String email = CampoEmailFun.getText();
        String CPF = CampoCPFFun.getText();
        String empresa = CampoEmpresaFun.getText();
        
        Funcionario funcionario = new Funcionario();
        funcionario.setNome(nome);
        funcionario.setEmail(email);
        funcionario.setCPF(CPF);
        funcionario.setEmpresa(empresa);
        
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        funcionarioDAO.inserir(funcionario);
        
        CampoNomefun.setText("");
        CampoEmailFun.setText("");
        CampoCPFFun.setText("");
        CampoEmpresaFun.setText("");
        
        
        
        
    }//GEN-LAST:event_jButtonInserirFunActionPerformed

    private void CampoNomefunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomefunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomefunActionPerformed

    private void CampoCPFFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCPFFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCPFFunActionPerformed

    private void CampoEmpresaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmpresaFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmpresaFunActionPerformed

    private void CampoEmailFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailFunActionPerformed

    private void pesquisaIDFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaIDFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaIDFunActionPerformed

    private void jButtonPesquisafunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisafunActionPerformed
        // TODO add your handling code here:
        //botão pesquisa funcionário 
        
            int idPesquisa = Integer.parseInt(pesquisaIDFun.getText());
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            Funcionario funcionario = funcionarioDAO.getFuncionario(idPesquisa);
            if (funcionario == null){
                JOptionPane.showMessageDialog(this,"Funcionário não encontrado:(");
            }
            
            else{
                
                
                jTextFieldID.setText(String.valueOf(funcionario.getId()));
                CampoNomefun.setText(funcionario.getNome());
                CampoEmailFun.setText(funcionario.getEmail());
                CampoCPFFun.setText(funcionario.getCPF());
                CampoEmpresaFun.setText(funcionario.getEmpresa());
                
            }

            



    }//GEN-LAST:event_jButtonPesquisafunActionPerformed

    private void EditarfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarfunActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextFieldID.getText());
        String nome = CampoNomefun.getText();
        String email = CampoEmailFun.getText();
        String CPF = CampoCPFFun.getText();
        String empresa = CampoEmpresaFun.getText();
        
        Funcionario funcionario = new Funcionario();
        funcionario.setId(id);
        funcionario.setNome(nome);
        funcionario.setEmail(email);
        funcionario.setCPF(CPF);
        funcionario.setEmpresa(empresa);
        
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        funcionarioDAO.editar(funcionario);
        
        jTextFieldID.setText("");
        CampoNomefun.setText("");
        CampoEmailFun.setText("");
        CampoCPFFun.setText("");
        CampoEmpresaFun.setText("");



    }//GEN-LAST:event_EditarfunActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt( jTextFieldID.getText());
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        funcionarioDAO.excluir(id);
        
        jTextFieldID.setText("");
        CampoNomefun.setText("");
        CampoEmailFun.setText("");
        CampoCPFFun.setText("");
        CampoEmpresaFun.setText("");
        



    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        // TODO add your handling code here:
        menuRelatorioFun rf = new menuRelatorioFun();
        rf.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCPFFun;
    private javax.swing.JTextField CampoEmailFun;
    private javax.swing.JTextField CampoEmpresaFun;
    private javax.swing.JTextField CampoNomefun;
    private javax.swing.JButton Editarfun;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserirFun;
    private javax.swing.JButton jButtonPesquisafun;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField pesquisaIDFun;
    // End of variables declaration//GEN-END:variables
}
